전남대 FE_강호정 5주차 과제 Step1
kakao-tech-campus-2nd-step2/react-product-login pull request #10
Opened 2024-07-23 12:34 UTC by hojeong26

안녕하세요 멘토님!!
5주차 과제를 진행해보았습니다. 테스트 코드를 작성하는게 이번 과제의 주요 과제였는데 솔직히 잘 안됐습니다. 그래서 멘토님께 피드백을 받고자 pr을 보냈습니다.

이번주도 잘 부탁드립니다.

**궁금한점**
- 다른 파일에서 컴포넌트를 불러올 때 자꾸 에러가 뜹니다. 이유가 궁금합니다
<img width="365" alt="스크린샷 2024-07-23 213339" src="https://github.com/user-attachments/assets/259ae23c-c91a-484c-82af-5c740d199ba9">

2024-07-23 14:47 UTC, wacilpong commented
@hojeong26 
안녕하세요 호정님! 열심히 테스트코드를 작성중이시군요. 모든 에러는 로그에 힌트가 가장 잘 나와있는데요,
import문에서 `~value is never read` 에러가 떴다는 것은 현재 컨텍스트에서 사용하지 않았음을 의미하는데,  호정님은 분명 render()함수안에서 쓰고 있습니다. 그러면 render 함수쪽에서 어떤 에러가 나는지 볼까요?

`'GoodsDetailHeader' refers to a value, but is being used as a type here. Did you mean 'typeof GoodsDetailHeader'?`

뭔가 GoodsDetailHeader라는 것은 값(value)인 것 같은데, 타입으로 쓰이고 있다는 에러가 뜹니다. `<GoodsDetailHeader />`는 리액트 컴포넌트인데 이를 컴포넌트로 인식하고 있지 못한 것이죠.(아마 제 추측상 제네릭 타입 정도로 취급되고 있는 듯합니다.) 그럼 왜 이 리액트 컴포넌트 문법을 ts에서 인식하지 못할까요? jsx문법임을 알려주려면 어떻게 해야할까요? 테스트파일이더라도 리액트 컴포넌트를 테스트한다는 것을 잊지 마세요. 그리고 타입스크립트에서의 jsx는 `.tsx`확장자를 갖고 있습니다.

충분한 힌트가 되었을까요? ㅎㅎ

2024-07-24 03:22 UTC, wacilpong requested changes
@hojeong26 
안녕하세요 호정님! 열심히 테스트코드를 작성중이시군요. 모든 에러는 로그에 힌트가 가장 잘 나와있는데요,
import문에서 `~value is never read` 에러가 떴다는 것은 현재 컨텍스트에서 사용하지 않았음을 의미하는데,  호정님은 분명 render()함수안에서 쓰고 있습니다. 그러면 render 함수쪽에서 어떤 에러가 나는지 볼까요?

`'GoodsDetailHeader' refers to a value, but is being used as a type here. Did you mean 'typeof GoodsDetailHeader'?`

뭔가 GoodsDetailHeader라는 것은 값(value)인 것 같은데, 타입으로 쓰이고 있다는 에러가 뜹니다. `<GoodsDetailHeader />`는 리액트 컴포넌트인데 이를 컴포넌트로 인식하고 있지 못한 것이죠.(아마 제 추측상 제네릭 타입 정도로 취급되고 있는 듯합니다.) 그럼 왜 이 리액트 컴포넌트 문법을 ts에서 인식하지 못할까요? jsx문법임을 알려주려면 어떻게 해야할까요? 테스트파일이더라도 리액트 컴포넌트를 테스트한다는 것을 잊지 마세요. 그리고 타입스크립트에서의 jsx는 `.tsx`확장자를 갖고 있습니다.

충분한 힌트가 되었을까요? ㅎㅎ

(알림이 안간거같아서 리퀘스트체인지로 다시 보내드려요~)

2024-07-24 04:18 UTC, hojeong26 commented
!! 감사합니다🥹🥹🥹 생각지도 못했는데 그런 문제가 발생할 수도 있겠군요...

2024-07-24 09:09 UTC, wacilpong approved these changes
리뷰할 것이 크게 없어서 확장자 고쳐주시면 step1 머지하겠습니다~

2024-07-24 12:03 UTC, hojeong26 commented
push 했습니다!

2024-07-24 12:31 UTC, merged