부산대 FE_이세형 Step 0.5
kakao-tech-campus-2nd-step2/react-product-login pull request #12
Opened 2024-07-23 17:25 UTC by cla6shade

안녕하세요 멘토님-!

레거시 API에서 최신 API로 옮기는 중에 변경사항이 너무 많아서, 
리뷰에 방해가 될 것 같아 미리 마이그레이션 된 코드로 PR 보냅니다!

감사합니다.

2024-07-23 23:31 UTC, MiaJLee requested changes
세형님~ 주석이 남아있어서 요거만 확인해주세요-!

2024-07-23 23:31 UTC, MiaJLee commented on src/components/organisms/main/ranking/RankingProductDisplayArea.tsx
> +        {/* /> */}
여기 주석은 임시로 처리하신걸까요??

2024-07-24 04:05 UTC, cla6shade commented on src/components/organisms/main/ranking/RankingProductDisplayArea.tsx
> +        {/* /> */}
저부분은 향후 개발 스펙에서 완전히 제외돼서, 리팩토링 하기도 애매하고 그렇다고 아예 없애버리자니 적어논 코드가 아깝고,, 없애지 않으니 에러가 발생해서 일단 주석으로 두었습니다.

혹시 이럴땐 어떻게 처리해야 하는지 궁금합니다!

2024-07-24 05:03 UTC, MiaJLee commented on src/components/organisms/main/ranking/RankingProductDisplayArea.tsx
> +        {/* /> */}
@cla6shade 
불가피하게 주석을 적는 경우 위에 왜 주석처리로 남겨두었는지 추가해두면 좋습니다-!
언제 제거할 예정인지 등의 정보를 주석으로 추가할 수 있겠습니다~

앞으로 사용되는것이 아니면 아깝더라도 지우는 것이 좋을 것 같아요!

2024-07-24 05:10 UTC, cla6shade commented on src/components/organisms/main/ranking/RankingProductDisplayArea.tsx
> +        {/* /> */}
넵 알겠습니다! 그러면 해당 코드를 아예 제거한 후 푸쉬하겠습니다-!

2024-07-24 09:00 UTC, MiaJLee approved these changes
고생하셨습니다~ 👍

2024-07-24 09:00 UTC, merged