전남대 FE_정서윤 5주차 과제 step1
kakao-tech-campus-2nd-step2/react-product-login pull request #16
Opened 2024-07-24 14:12 UTC by yunn23

안녕하세요 멘토님 5주차도 잘 부탁드립니다!

- 현재 테스트 코드를 작성한 후 테스트 실행을 해보면 모듈을 찾을 수 없다는 오류가 발생하고 있습니다. jest가 경로 설정을 못하고 있나 싶어 jest 설정 파일과 바벨 설정 파일을 추가해서 경로 오류를잡아보려하였지만 오류가 지속되어 어떤 부분을 수정해야 할지 도움을 청하고 싶습니다. 또, 테스트케이스를 처음 작성해보는거라 생소한데 올바른 방식으로 작성했는지도 궁금합니다!

- 오류 화면 첨부합니다.
<img width="937" alt="image" src="https://github.com/user-attachments/assets/7755f527-2d26-47ee-b307-f40693d5eb69">

2024-07-26 01:34 UTC, taehwanno requested changes
빠르게 먼저 피드백드려요.

2024-07-26 01:34 UTC, taehwanno commented on jest.config.js
> +
craco를 사용하고 있기 때문에 jest.config.js 보다는 이에 맞춰 설정해주시면 동작하실 거 같아요. 지금은 jest 정의가 package.json, jest.config.js, craco 3가지가 가능해보이는데 craco로 몰아서 관리하는게 좋겠습니다.

- [Jest - CRACO](https://craco.js.org/docs/configuration/jest/)

2024-07-26 07:29 UTC, yunn23 commented on jest.config.js
> +
마감기한까지 시간이 촉박해서 step3까지 모두 구현한 이후 수정하도록 하겠습니다!

2024-07-27 16:11 UTC, yunn23 commented
jest의 설정을 craco 한 곳에서만 관리해 모듈을 찾을 수 없다는 오류는 해결되었지만, 현재 jest가 ES6 import문을 처리하지 못하는 문제가 발생하고 있습니다. 처음엔 babel로 설정하였다가, 서칭중 babel과 충돌이 있을 수 있다는 글을 보고 ts-jest를 설치하였지만 계속 오류가 지속되고 있습니다. 혹시 어떤 부분이 문제일까요??

2024-07-28 13:58 UTC, taehwanno requested changes
피드백 드려요.

2024-07-28 13:58 UTC, taehwanno commented on craco.config.js
> +      return jestConfig;
아래처럼 함수가 아니라 객체를 바로 configure 속성에 전달할 수도 있네요. 참고 부탁드려용

```js
jest: {
  configure: {
    transform: {
      // ...
    },
    // ...
  },
}
```

2024-07-28 13:58 UTC, taehwanno commented on craco.config.js
> +    configure: (jestConfig, { env, paths, resolve, rootDir }) => {
> jest의 설정을 craco 한 곳에서만 관리해 모듈을 찾을 수 없다는 오류는 해결되었지만, 현재 jest가 ES6 import문을 처리하지 못하는 문제가 발생하고 있습니다. 처음엔 babel로 설정하였다가, 서칭중 babel과 충돌이 있을 수 있다는 글을 보고 ts-jest를 설치하였지만 계속 오류가 지속되고 있습니다. 혹시 어떤 부분이 문제일까요??

`preset: 'ts-jest'`이 설정이 안된 거 같아요. 그리고 craco의 오류인지는 잘 모르겠는데 transformIgnorePatterns가 정의되더라도 node_modules 하위에 있는 코드를 transpile 하도록 해야하는데 동작하지 않는거 같군요. package.json의 test script를 아래처럼 변경해서 실행하니 테스트 동작하는 것 확인했습니다.

```json
"test": "craco test --transformIgnorePatterns \"node_modules/(?!(axios|@tanstack|react-query))/\"",
```

2024-07-28 13:58 UTC, taehwanno commented on src/components/features/Order/OrderForm/index.test.tsx
> +  test('should return error when cash receipt number is missing', () => {
테스트 코드의 명세는 영어로 작성해도 충분하긴 한데 한글이 모국어인 개발자 분들과 협업하다보면 영어로는 각자 해석이 달라질 수 있어서 테스트 명세를 잘못 이해하는 경우가 간혹 있더라구요. 추후 협업하실 때 소속된 팀에서 한번 논의해보시는게 좋을 내용이라 언급해두고 넘어갈게요. 테스트가 깨졌을 때 과거의 내가 작성해놓은 것을 미래의 내가 읽을 때 중요할 뿐만 아니라 다른 동료 개발자가 작성해둔 테스트 명세가 명확해야 테스트로 기대하는 결과가 예상 가능하고 테스트 코드를 수정해야할지 변경한 코드를 개선해야할지 쉽게 알 수 있더라구요. 이는 팀 생산성과 연결되는 문제이고 팀의 테스트 작성 경험에도 중요한 영향을 미치게 됩니다.

2024-07-28 13:58 UTC, taehwanno commented on src/components/features/Order/OrderForm/index.test.tsx
> +    expect(result.errorMessage).toBe('현금영수증 번호를 입력해주세요.');
해당 함수의 내부 구현을 살펴보면 총 4가지의 상황이 가능보이는데 그중 아래 2가지 유효성 관련 검증은 테스트 케이스로 작성하지 않으신 이유는 무엇인지 궁금합니다.

1. 현금영수증 번호는 숫자로만 입력해주세요.
2. 메시지를 입력해주세요.

2024-07-28 13:58 UTC, taehwanno commented on src/pages/Goods/Detail/index.test.tsx
> +import { worker } from '@/mocks/browser';
msw가 browser 환경이 아닌 node.js에서 실행되다보니 msw의 node.js에 맞게 실행될 수 있도록 테스트 코드를 구성해주셔야 올바르게 API가 mocking 될 수 있습니다.

- https://mswjs.io/docs/integrations/node

2024-07-28 13:58 UTC, taehwanno commented on src/pages/Goods/Detail/index.test.tsx
> +  useGetProductOptions: jest.fn(),
mocking path가 잘못된 거 같아요.

```suggestion
jest.mock('@/api/hooks/useGetProductDetail', () => ({
  useGetProductDetail: jest.fn(),
}));

jest.mock('@/api/hooks/useGetProductOptions', () => ({
```

2024-07-29 06:56 UTC, yunn23 commented on src/components/features/Order/OrderForm/index.test.tsx
> +    expect(result.errorMessage).toBe('현금영수증 번호를 입력해주세요.');
테스트 코드 작성후 테스트를 해보면서 오류에 초점을 맞추다 보니 추가로 테스트 케이스를 작성해야한다는 것을 잊어버린 것 같습니다. 위 2가지 상황에 대한 테스트 케이스도 작성하였습니다!

2024-07-29 14:27 UTC, taehwanno approved these changes
고생하셨어요!

2024-07-29 14:27 UTC, merged