부산대 FE_한재안 5주차 Step1
kakao-tech-campus-2nd-step2/react-product-login pull request #22
Opened 2024-07-24 22:09 UTC by JaeanHan

안녕하세요 멘토님! Step 1 완료 후 제출 합니다!
제가 테스트 코드 작성은 처음이라, GPT와 공식 문서를 엄청 읽으며 동작하는 코드는 만들긴 했으나, 개선이 필요한 코드인 것 같습니다 ㅠㅠ! 그런데 어떻게 개선해야 하는지 전혀 감이 잡히지 않아 도움을 구하고 싶습니다..

추가적으로 제가 Step1을 진행 중 클릭 이벤트가 발생하지 않는 문제를 겪었습니다.
`fireEvent`를 통해 아무리 click이벤트를 발생 시키려고 해도, checkbox와 같은 요소엔 적용이 안됐는데, 
원인을 모르겠습니다 ㅠㅠ..  클릭 이벤트가 발생하지 않으니 결국 값을 직접 바꿔서 테스트를 진행했습니다 ㅠㅠ..
`오더테스트`를 확인해 주시면 감사하겠습니다..!
`fireEvent(screen.getByLabelText(/현금영수증 신청/i), new MouseEvent('click', { bubbles: true }));`

2024-07-25 04:13 UTC, wacilpong commented
@JaeanHan 
안녕하세요 재안님~ 문법에 틀린 부분은 없어보이는데.. 혹시 아래와 같이 해도 똑같이 작동하지 않은지 확인해주실 수 있나요?

`fireEvent.click(screen.getByLabelText(/현금영수증 신청/i));`

만약 그렇다면 `screen.getByLabelText(/현금영수증 신청/i)` 이 부분이 제대로 요소를 가져오고 있는지 한번 확인해보세요.
정규식이 잘못 걸려서 요소가 셀렉되지 않은 상태일 수도 있습니다.

2024-07-25 06:03 UTC, wacilpong reviewed
@JaeanHan 
안녕하세요 재안님~ 문법에 틀린 부분은 없어보이는데.. 혹시 아래와 같이 해도 똑같이 작동하지 않은지 확인해주실 수 있나요?

`fireEvent.click(screen.getByLabelText(/현금영수증 신청/i));`

만약 그렇다면 `screen.getByLabelText(/현금영수증 신청/i)` 이 부분이 제대로 요소를 가져오고 있는지 한번 확인해보세요.
정규식이 잘못 걸려서 요소가 셀렉되지 않은 상태일 수도 있습니다.

2024-07-25 06:10 UTC, JaeanHan commented
@wacilpong 
제공해 주신 코드로도 해봤는데 fireEvent가 동작하지 않습니다. ㅠㅠ
제가 접근하고 싶은 요소는 아래와 같이 이루어져 있습니다.
```
<Controller
        control={control}
        name="hasCashReceipt"
        render={({ field: { onChange, value, ref } }) => (
          <Checkbox
            ref={ref}
            onChange={onChange}
            isChecked={value}
            colorScheme="yellow"
            size="lg"
            role="checkbox"
            data-testid="cashcheck"
            aria-checked={false}
          >
            <LabelText>현금영수증 신청</LabelText>
          </Checkbox>
        )}
      />
```

아래와 같은 시도를 했습니다.

```
test('오더테스트', async () => {
  orderHistorySessionStorage.set({
    id: 3245119,
    count: 3,
  });

  const { debug } = renderWithProviders(<OrderPage />);

  await waitForElementToBeRemoved(() => screen.queryByRole('spinner'), { timeout: 5000 });

  const cashReceiptCheckbox = screen.getByLabelText(/현금영수증 신청/i);
  const cashReceiptCheckBoxTestId = screen.getByTestId('cashcheck');
  const cashReceiptCheckboxByRole = screen.queryByRole('checkbox');

  debug(cashReceiptCheckbox); //  d1

  debug(cashReceiptCheckBoxTestId); // d2

  // debug(cashReceiptCheckboxByRole); // null이라 전체 트리가 찍힘

  fireEvent.click(cashReceiptCheckbox);
  fireEvent.click(cashReceiptCheckBoxTestId);
  // fireEvent.click(cashReceiptCheckboxByRole); // Unable to fire a "click" event - please provide a DOM element.
  cashReceiptCheckBoxTestId.click(); // 라벨이니까 클릭

  expect(cashReceiptCheckbox).toBeChecked(); // e1
});


```

위의 코드를 실행하면, 아래 사진과 같이 요소를 잘 가져오는 것을 확인할 수 있습니다.
```
// d1 : 정확히 인풋이 선택됩니다.
console.log
    <input
      class="chakra-checkbox__input"
      style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; width: 1px; margin: -1px; padding: 0px; overflow: hidden; white-space: nowrap; position: absolute;"   
      type="checkbox"
      value=""
    />

// d2 : 라벨이 선택됩니다.
 console.log
    <label                                                                                                                                                                   
      class="chakra-checkbox css-1577qb8"                                                                                                                                    
      data-testid="cashcheck"                                                                                                                                                
      role="cashcheck"                                                                                                                                                       
    >                                                                                                                                                                        
      <input
        class="chakra-checkbox__input"
        style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; width: 1px; margin: -1px; padding: 0px; overflow: hidden; white-space: nowrap; position: absolute;" 
        type="checkbox"
        value=""
      />
      <span
        aria-hidden="true"
        class="chakra-checkbox__control css-qqkdt0"
      />
      <span
        class="chakra-checkbox__label css-r90m2q"
      >
        <span
          class="css-jkowxj"
        >
          현금영수증 신청
        </span>
      </span>
    </label>

```

```
// e1
expect(element).toBeChecked()                                                                                                                                            
                                                                                                                                                                             
    Received element is not checked:                                                                                                                                         
      <input class="chakra-checkbox__input" style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; width: 1px; margin: -1px; padding: 0px; overflow: hidden; white-space: nowrap; position: absolute;" type="checkbox" value="" />
```

현재 방법으로도 요소는 잘 가져와 지는 것 같습니다.
role, test-id를 통한 방법으로는 해당 속성이 라벨에 할당되어 인풋 요소가 선택이 안됩니다.

만약 `screen.getByLabelText(/현금영수증 신청/i)` 방법으로 인풋 요소가 정확히 선택되지 않았다면, `cashReceiptCheckbox.checked = true`가 적용이 안됐어야 하는데 이건 또 적용이 됩니다. 

문법 이슈도 없고, 요소 선택도 잘 되는데, 왜 `fireEvent`만 안되는지.. 어제 이거에만 시간을 정말 많이 쏟았습니다 ㅠㅠ
 `fireEvent` 이슈를 해결 해야 submit 이벤트를 발생시켜 다른 밸리데이션 통합 테스트를 진행 할 수 있을 거 같아 질문 드립니다... 😭😭

2024-07-25 15:43 UTC, wacilpong requested changes
@JaeanHan 
안녕하세요 재안님! 제가 야간업무로 인해 이제야 확인해보았는데요~
제가 로컬에서 돌려보기로는 fireEvent가 잘 실행되고 있는데요, 혹시 어떤 로그나 현상을 보고 안된다고 하신건지 좀더 말씀해주시겠어요?

아래 로그를 보면 true로 잘 찍히고(fireEvent.click은 불리언을 반환함),
`console.log(fireEvent.click(screen.getByLabelText(/현금영수증 신청/i)));`

아래처럼 일부러 틀린 라벨텍스트로 요소를 가져와서 Click하려고 하면 테스트가 FAIL이 됩니다.
`console.log(fireEvent.click(screen.getByLabelText(/현금영수증 신청111/i)));`

fireEvent가 안된다는 것이 어떤 의미인지 좀더 자세히 말씀해주시겠어요? 그리고 간단한 코멘트 남겼으니 확인부탁드립니다~

2024-07-25 15:43 UTC, wacilpong commented on src/api/hooks/products.mock.ts
> +    }
별건 아니지만 else 안의 return은 불필요해서 else를 제거해도 됩니다. (린트 룰로도 있습니다: https://eslint.org/docs/latest/rules/no-else-return)

2024-07-25 15:43 UTC, wacilpong commented on src/pages/Order/index.tsx
> +  // if (!orderHistory) return <LoadingView />;
사용하지 않는 코드는 지우거나, 주석을 할 경우 웬만하면 이유를 적는 것이 좋습니다.

2024-07-25 15:43 UTC, wacilpong commented on src/tests/order.test.tsx
> +  const cashReceiptNumberInput = screen.getByPlaceholderText('(-없이) 숫자만 입력해주세요.');
이 3개는 HTMLInputElement이므로 타입을 지정해주어야 다른 타입에러가 발생하지 않을 듯합니다.

```
  const cashReceiptCheckbox = screen.getByLabelText<HTMLInputElement>(/현금영수증 신청/i);
  const cashReceiptTypeSelect = screen.getByTestId<HTMLInputElement>('cashReceiptType');
  const cashReceiptNumberInput = screen.getByPlaceholderText<HTMLInputElement>('(-없이) 숫자만 입력해주세요.');
```

2024-07-25 16:27 UTC, JaeanHan commented
@wacilpong 
엇 일단 제가 못하고 있던 클릭 관련 부분은 해결했습니다!
클릭 이벤트가 발생했다면, checked 값이 당연히 바꿔야 하는데 왜 안 바뀌지? 라는 생각에 클릭 이벤트가 발생 안되나..?라고 생각했습니다. 일단 해당 부분은 userEvent 라이브러리의 버전을 올리며 해결했습니다!

2024-07-25 16:30 UTC, JaeanHan commented on src/api/hooks/products.mock.ts
> +    }
앗..! 수정하겠습니다. 제가 step1을 진짜 정신없이 구현해서 미쳐 신경 쓰지 못한 부분입니다 ㅠㅠ!

2024-07-25 16:36 UTC, JaeanHan commented on src/pages/Order/index.tsx
> +  // if (!orderHistory) return <LoadingView />;
아 제가 디버깅 용도로 잠시 바꾸었던 코드입니다.
이번 주 step1 과제 구현이 잘 안되어 마음이 많이 조급했었습니다. 그런 과정에 신경 써야 하는 부분을 많이 놓친 것 같습니다 ㅠㅠ. 앞으로는 너무 조급해 하지 않고 조금 더 여유를 갖고 진행하려 노력하겠습니다 ㅠㅠ!
디버깅 용도의 코드를 지우고 원래 있던 코드를 복원하겠습니다!

2024-07-25 16:38 UTC, JaeanHan commented on src/tests/order.test.tsx
> +  const cashReceiptNumberInput = screen.getByPlaceholderText('(-없이) 숫자만 입력해주세요.');
참고해서 수정하겠습니다. 감사합니다!

2024-07-26 09:39 UTC, wacilpong approved these changes
아하 라이브러리 버전 문제였나보군요! 찾느라 고생하셨겠어요. 의존성끼리 버전 충돌나거나 설정관련 문제가 생겼을 때 소위 '삽질'을 하면 정말 고생이거든요.. 그래도 미리미리 이런 트러블슈팅들을 잘 정리해두면 연차가 쌓일수록 분명 도움이 됩니다 👍👍 스텝1 수고많으셨고, 머지하겠습니다~!

2024-07-26 09:39 UTC, merged