강원대 FE_허윤수 5주차 과제 STEP1-test
kakao-tech-campus-2nd-step2/react-product-login pull request #36
Opened 2024-07-25 17:55 UTC by sugoring

안녕하세요, 멘토님!

피드백을 위해 귀한 시간 내주셔서 감사합니다.

2024-07-28 06:49 UTC, danmin20 commented
1. 어떤 라이브러리든 무조건 최신이 사용하는 게 정답은 아니에요. 기존 다른 라이브러리들과의 충돌이 있을 수도 있고요. 그건 상황마다 다를 것 같습니다~

2. 테스트코드 작성 시 describe를 더 알아보기 쉽게 한다든가 하는 방법이 있을 것 같습니다.

2024-07-28 06:55 UTC, danmin20 requested changes
수고하셨습니다~

2024-07-28 06:55 UTC, danmin20 commented on src/api/hooks/useGetProductDetail.test.tsx
> +    });
쿼리 훅에 대해서 테스트를 할 필요가 있을까?하는 의문은 들어요. 어차피 서버에서 뿌려주는 데이터를 가져오는 부분일 뿐이라.. 클라이언트 측 로직을 담당하는 훅이나 유틸, 페이지 시나리오에 대해서 테스트를 작성하는 게 훨씬 도움이 될 것 같아요.

2024-07-28 06:55 UTC, danmin20 commented on src/api/hooks/useGetCategorys.ts
>  const categoriesQueryKey = [getCategoriesPath()];
따로 빼주신 이유가 있을까요?

2024-07-28 06:55 UTC, danmin20 commented on src/api/hooks/productDetail.mock.ts
> +});
이 스키마를 사용해서 submit시에 parse해서 체크해볼 수도 있겠네요~

2024-07-28 06:59 UTC, danmin20 commented
리드미 컨플릭트는 제가 임의로 수정하겠습니다~

2024-07-28 06:59 UTC, merged

2024-07-29 12:00 UTC, sugoring commented on src/api/hooks/useGetProductDetail.test.tsx
> +    });
데이터를 가져오는 부분이 아직 익숙하지 않아서 해당 설정에 대한 테스트를 하고 싶습니다! 말씀해주신 내용을 참고하여 프론트엔드 자체의 로직 테스트도 함께 진행해보겠습니다. 감사합니다 ㅎㅎ