강원대 FE_허윤수 5주차 과제 STEP2-wish
kakao-tech-campus-2nd-step2/react-product-login pull request #42
Opened 2024-07-26 06:34 UTC by sugoring

## 2단계 -  위시 리스트
  
- 상품 상세 페이지
  - [x] 위시 등록 버튼 UI 구현
  - [x] 위시 등록 버튼 로직 구현: 위시 등록 성공 시 "위시 등록 완료" Alert 메시지 표시

- 마이 페이지
  - [x] 위시 목록 리스트 UI 구현: Chakra UI 컴포넌트 활용
  - [x] 위시 목록 API 활용: 선물하기 API 노션의 response 데이터 활용
  - [x] 위시 목록 리스트 로직 구현: 위시 삭제 성공 시 해당 항목 리스트에서 제거

2024-07-28 07:07 UTC, danmin20 commented
브랜치 작업이 별개의 작업이 아니라 이어지는 거라면, 이전 브랜치에서 따오는 것도 괜찮아요~ 오히려 무조건 메인에서 따다보면 컨플릭트가 발생할 수도 있어요.

2024-07-28 07:09 UTC, danmin20 commented
질문주신 에러부분은 상황마다 다를 수 있어서, 저도 알아봐야 하는 부분이라..ㅎㅎ 우선 구글링으로 해보시면 좋을 것 같습니다. 저도 한번 알아볼게요!

2024-07-28 08:49 UTC, danmin20 requested changes
수고하셨습니다~

2024-07-28 08:49 UTC, danmin20 commented on src/api/hooks/useGetLogin.ts
> +  return response.json();
보통은 서버쪽에서 에러메시지를 같이 넘겨줄 것 같아요. 지금은 fetch를 사용하셨지만 axiosInstance 만드실 때 인터셉터로 처리하는 것도 좋아보여요~

2024-07-28 08:49 UTC, danmin20 commented on src/api/hooks/useGetWishList.ts
> +export const useRemoveWish = () => {
저는 보통 useQuery를 사용할 경우에는 useXXXQuery, useMutaiontion을 사용할 경우에는 useXXXMutaion 정도로 네이밍하는 편이에요~

2024-07-28 08:49 UTC, danmin20 commented on src/api/mocks/login.mock.ts
> +
타입들도 모킹, 실제 훅에서 동일하게 쓰인다면 같이 묶어주세요~

2024-07-28 08:49 UTC, danmin20 commented on src/components/common/Icons/HeartIcon.tsx
> +    </svg>
저라면 .svg로 저장하고, svgr같은 라이브러리 사용해서 옵션 넣어줄 것 같아요~

2024-07-28 08:49 UTC, danmin20 commented on src/api/hooks/useGetCategorys.test.tsx
> +import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
엔트포인트별로 폴더링을 하는 것도 좋아보여요.
```
hooks/category
hooks/product
```
그리고 category복수형 categories가 되어야할 것 같아요~

2024-07-28 08:49 UTC, merged

2024-07-30 06:38 UTC, sugoring commented on src/api/hooks/useGetLogin.ts
> +  return response.json();
반영하였습니다!

2024-07-30 07:38 UTC, sugoring commented on src/api/hooks/useGetWishList.ts
> +export const useRemoveWish = () => {
반영했습니다!

2024-07-30 07:56 UTC, sugoring commented on src/api/mocks/login.mock.ts
> +
반영했습니다!

2024-07-30 16:05 UTC, sugoring commented on src/components/common/Icons/HeartIcon.tsx
> +    </svg>
반영하였습니다!

2024-07-30 16:06 UTC, sugoring commented on src/api/hooks/useGetCategorys.test.tsx
> +import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
반영하였습니다!