부산대 FE_이세형 5주차 과제 Step3
kakao-tech-campus-2nd-step2/react-product-login pull request #46
Opened 2024-07-26 07:42 UTC by cla6shade

안녕하세요 멘토님!

step 2에 이어서 step 3 PR 보내드립니다.

감사합니다!

2024-07-26 08:45 UTC, MiaJLee requested changes
세형님~ head 브랜치 한번 당겨주세요!

2024-07-26 13:24 UTC, cla6shade commented
conflict 해결했습니다.
감사합니다!

2024-07-27 01:13 UTC, MiaJLee commented
@cla6shade 세형님~
[1a5c7dc](https://github.com/kakao-tech-campus-2nd-step2/react-product-login/pull/46/commits/1a5c7dc635e2e4f80fd0a340ea466a6f5440defc) 에서 질문 답변 작성하신게 제거된 것 같아요~

2024-07-27 02:00 UTC, cla6shade commented
제가 확인을 하지 않고 `Accept theirs`를 누른 후 그대로 푸쉬해서 문제가 생긴 것 같습니다.

죄송합니다..

2024-07-27 14:00 UTC, MiaJLee approved these changes
LGTM👍🏻👍🏻 고생하셨습니다 :)

2024-07-27 14:00 UTC, merged