Step2
kakao-tech-campus-2nd-step2/react-product-login pull request #50
Opened 2024-07-26 08:48 UTC by dlwltn0430

2024-07-26 13:21 UTC, MiaJLee requested changes
지수님 고생하셨습니다~ 몇가지 개선사항 남겼는데 확인 부탁드려요!

2024-07-26 13:21 UTC, MiaJLee commented on src/api/hooks/wishlist.mock.ts
> +  rest.delete(`${BASE_URL}/api/wishes/:id`, (req, res, ctx) => {
```suggestion
  rest.delete(`${getWishlistPath()}/:id`, (req, res, ctx) => {
```
위와 같이 작성하면 좀 더 일관성 있는 코드가 될 것 같아요-!

2024-07-26 13:21 UTC, MiaJLee commented on src/api/hooks/useLogin.ts
> +      const redirectUrl = queryParams.get('redirect') ?? `${window.location.origin}/`;
```suggestion
      const redirectUrl = queryParams.get('redirect') ?? window.location.origin;
```
위 코드와 동일하지 않을까요?

2024-07-26 13:21 UTC, MiaJLee commented on src/api/hooks/useGetWishlist.ts
> +export const getWishlistPath = () => `${BASE_URL}/api/wishes`;
상수가 아닌 함수로 작업하신 이유가 있을까요?
```suggestion
export const WISH_LIST_PATH = `${BASE_URL}/api/wishes`;
```

2024-07-26 13:21 UTC, MiaJLee commented on src/api/hooks/useDeleteWishlistItem.ts
> +  await fetchInstance.delete(`${BASE_URL}/api/wishes/${wishId}`, {
여기도 getWishlistPath 함수를 사용할 수 있겠어요.

2024-07-26 13:21 UTC, MiaJLee commented on src/api/hooks/auth.mock.ts
> +        ctx.status(200),
에러코드 상수도 enum, type 등으로 만들어서 default error message와 연결시킬 수 있을 것 같아요~
단, 모든 api에 적용될 수 있는 포괄적인 메세지가 좋겠지요!
ex) `ERROR_CODE.Unauthorized`, `401`, `“권한이 없습니다.”`

2024-07-27 19:31 UTC, dlwltn0430 commented on src/api/hooks/useGetWishlist.ts
> +export const getWishlistPath = () => `${BASE_URL}/api/wishes`;
`src/api/hooks/useGetCategorys.ts` 참고해서 코드 작성하다보니 함수로 작성한 것 같아요! 상수로 수정했습니다😊

2024-07-28 04:27 UTC, MiaJLee approved these changes
LGTM! 고생하셨습니다~

2024-07-28 04:27 UTC, merged