충남대 FE_김지안_5주차 과제
kakao-tech-campus-2nd-step2/react-product-login pull request #53
Opened 2024-07-26 11:06 UTC by KimJi-An

안녕하세요 멘토님, 충남대학교 김지안 입니다.

5주차 과제 제출합니다.

2024-07-27 00:38 UTC, taehwanno requested changes
피드백 드려요!

2024-07-27 00:38 UTC, taehwanno commented on tests/OrderForm.test.tsx
> +  );
생각해볼만한 몇가지 의견을 말씀드리고 지나갈게요.

`item`, `queryClient` 같은 경우 테스트 실행에 필요한 의존성으로 선언되어서 여러 테스트 케이스에서 공유되어 사용되고 있네요. 특정 테스트 케이스만을 위해 공유되고 있는 값이 변경돼야할 때 기존에 있던 테스트가 의도치 않게 실패 해야하는데 성공하거나 (False Negative), 성공해야하는데 실패하는 (False Positive) 상황이 발생할 수 있어요. ([해당글](https://gyuwon.github.io/blog/2018/12/19/false-positive-in-software-testing.html) 참고) 이는 테스트를 지속적으로 신뢰할 수 있는지 여부와 관련되어 있어서 중요한 문제이기도 합니다.

이를 [Avoid Nesting when you're Testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing), [AHA Testing](https://kentcdodds.com/blog/aha-testing)을 보면 `setup`을 만들어서 mutable variables를 지양하고 각 테스트 케이스마다 공유하는 것 없이 격리되어 실행할 수 있도록 가이드 하고 있어요.

`OrderForm.test.tsx` 코드에서 적용해본다면 `setup` 안에서는 `item` 기본값 지정하되 `setup` 함수로 특정값 전달해서 override 할 수 있도록 설정하고 `queryClient` 생성을 `setup`에서 해주는 방식이 있겠죠.

```tsx
// Test 1 (item 기본값 사용)
const {} = setup();

// Test 2 (item 특정값으로 override)
const {} = setup({ id: 123, count: 10 });
```

참고로 setup을 정의하더라도 지금 테스트 케이스에서는 item이 테스트 output에 영향을 주는 precondition 또는 input은 아니라서 Test 2 예시처럼 명시적으로 item을 setup에 전달해주지 않아도 괜찮습니다.

2024-07-27 00:38 UTC, taehwanno commented on tests/GoodsDetail.test.tsx
> +};
여러 테스트 케이스에서 공유해서 쓰고 있는 데이터가 있기에 OrderForm.test.tsx에서 드린 피드백을 동일하게 드릴 수 있겠습니다. OrderForm과는 다르게 GoodsData가 GoodsDetail.test.tsx 테스트 output에 영향을 미치는 테스트 input으로 동작하고 있기에 한번 개선해보시겠어요?

2024-07-27 00:38 UTC, taehwanno commented on tests/GoodsDetail.test.tsx
> +  });
```suggestion
  expect(name).toBeInTheDocument();
  expect(image).toBeInTheDocument();
  expect(price).toBeInTheDocument();
```

waitFor가 없어도 테스트 실행할거라 불필요한 await 같아요. 이런건 테스트 실행시간을 늦춰주는 원인이 되기에 정리해주는게 좋습니다.

2024-07-27 00:38 UTC, taehwanno commented on tests/GoodsDetail.test.tsx
> +  expect(decreaseButton).toHaveAttribute('aria-disabled', 'true');
```suggestion
  expect(decreaseButton).toBeDisabled();
```

`toBeDisabled`가 아니라 `aria-disabled` 속성 여부로 검증해야하는 이유는 무엇일까요? `disabled`가 적용되지 않고 `aria-disabled`만 적용되고 있어서 그런거라면, `aria-disabled`는 접근성 관련 요소라 사용자가 시각적으로 클릭할 수 없다는 것을 알 수 있게 `CountOptionItem` 컴포넌트 구현에 개선이 필요하다는 점을 테스트 작성 과정에서 발견해볼 수 있겠습니다.

2024-07-27 14:07 UTC, KimJi-An commented on tests/GoodsDetail.test.tsx
> +};
피드백 주신 내용을 반영하여 `setup` 함수를 통해 각 테스트 케이스에서 필요한 데이터를 준비하고, 필요한 경우 override를 통해 특정 테스트에서만 값을 변경할 수 있도록 수정해보았습니다.

2024-07-27 14:33 UTC, KimJi-An commented on tests/GoodsDetail.test.tsx
> +  expect(decreaseButton).toHaveAttribute('aria-disabled', 'true');
처음에는 `toBeDisabled`를 사용했었는데 적용되지 않아 찾아보니 Chakra UI에서는 disabled 속성 대신 `aria-disabled` 속성을 사용한다고 해서 `toHaveAttribute`를 사용해 `aria-disabled` 속성 여부로 검증해보았습니다.

2024-07-28 13:29 UTC, taehwanno approved these changes
고생하셨습니다.

2024-07-28 13:29 UTC, taehwanno commented on tests/GoodsDetail.test.tsx
> +  expect(decreaseButton).toHaveAttribute('aria-disabled', 'true');
그렇군요. disabled가 적용되지 않으면 button은 click이 가능할거라 onClick handler 호출이 가능하기 때문에 별도 처리를 해줘야할 거에요. `isDisabled`를 IconButton에서 지원하는거 같은데 이를 통해 해결될 수 있을지 한번 보면 좋을 거 같습니다.

2024-07-28 13:40 UTC, merged