강원대 FE_ 구희원 과제 제출합니다. (Step3)
kakao-tech-campus-2nd-step2/react-product-login pull request #60
Opened 2024-07-26 12:43 UTC by HeHelee

- 질문 1. Test code를 작성해보면서 좋았던 점과 아쉬웠던 점에 대해 말해주세요.
- 테스트 코드를 작성하면서 아쉬웠던 점은 단위 테스트 코드를 작성할 때 어떤 부분을 작성해야 할지 구분이 가지 않았습니다. util 폴더가 함수 폴더라고 생각해서 안에 있는 storage 관련해서 단위 테스트를 짰습니다. 그리고 추가적으로 더 짜고 싶은데 어떤 거를 짜면 좋을지 궁금합니다.
- 질문 2. 스스로 생각했을 때 좋은 컴포넌트란 무엇인지 본인만의 기준을 세우고 설명해 주세요.
제가 생각했을 때 좋은 컴포넌트는 재사용성이 높은 컴포넌트라고 생각합니다. 우선 저는 하나의 컴포넌트는 하나의 기능을 가져야 한다고 생각합니다. 왜냐하면 그렇게 해야 컴포넌트를 유지보수하고 테스트하기 쉽기 떄문입니다. 그래서 저도 이 부분을 고려해서 컴포넌트를 만들었던 거 같습니다. 그리고 다른 컴포넌트나 외부 상태에 의존하지 않도록 구성해야 한다고 생각합니다. 그래서 저도 필요한 데이터를 props를 통해서 전달받도록 했고, 외부 상태에 민감하게 반응하지 않도록 고려했습니다. 무엇보다도 확장 가능성이 중요하다고 생각합니다. 기본 기능을 변경하지 않고 새로운 기능을 추가하도록 만들어야 컴포넌트의 재사용성이 올라가기 때문입니다.
- 질문 3. 스스로 생각했을 때 공통 컴포넌트를 만들 때 가장 중요한 요소 2개를 선택하고 이유와 함께 설명해주세요.
공통 컴포넌트를 만들 때 가장 중요한 요소 2가지는 재사용성과 유연성이라고 생각합니다. 왜냐하면 재사용성은 코드 중복을 줄이고 일관성을 유지할 수 있게 해주며 유연성은 공통 컴포넌트가 다양한 요구사항과 맞게 쉽게 확장될 수 ㅇ 있게 해주어서 다양한 요구사항을 수용할 수 있어서 사용 범위가 넓어지기 때문입니다.

2024-07-27 12:28 UTC, yujo11 requested changes
안녕하세요 희원님~

미션 진행하느라 고생 많으셨습니다 API부분은 진행하다 잘 안 되시면 다시 질문 해주세요!

2024-07-27 12:28 UTC, yujo11 commented on src/api/hooks/fetchWishList.ts
> +export const useWishList = (page: number = 0, size: number = 10) => {
option도 사용하는 곳에서 parameter로 넘겨줄 수 있게 구현해보시면 좋을거 같아요

2024-07-27 12:28 UTC, yujo11 commented on src/api/hooks/fetchWishList.ts
> +export const useRemoveWish = () => {
여기도 위와 똑같이 option을 사용하는 곳에서 결정할 수 있으면 좋을거 같네요

2024-07-27 12:28 UTC, yujo11 commented on src/api/hooks/fetchWishList.ts
> +      queryClient.invalidateQueries({ queryKey: ['wishList'] });
localStorage나 queryKey처럼 `key` 값으로 사용되는 변수들은 상수로 관리해보시면 좋을거 같아요!

2024-07-27 12:28 UTC, yujo11 commented on src/components/features/Order/OrderForm/Order.test.tsx
> +  test('폼이 초기 값으로 렌더링 되는지 확인', async () => {
테스트명을 보고 어떤 상황에서 어떤 동작을 테스트하는지 명확히 알 수 있게 해주시면 좋을거 같아요

ex) 폼이 렌더될 때 초기값으로 xx와 cc를 가진다.

2024-07-27 12:28 UTC, yujo11 commented on src/components/features/Order/OrderForm/Order.test.tsx
> +import { fireEvent, render, screen, waitFor } from '@testing-library/react';
`userEvent`와 `fireEvent`의 차이에 대해서 찾아보시면 좋을거 같습니다!

2024-07-27 12:28 UTC, yujo11 commented on src/pages/FavoritesPage/index.tsx
> +          <List spacing={3}>
중첩 된 삼항연산자는 코드 가독성을 떨어트리는데요. 이 부분을 개선해 볼 수 있을까요?

2024-07-29 06:46 UTC, HeHelee commented on src/api/hooks/fetchWishList.ts
> +export const useWishList = (page: number = 0, size: number = 10) => {
넵 반영했습니다 ! option을 넣어주는 거는 어떤 훅에 주로 넣어주나요 ? 그것도 궁금합니다.

2024-07-29 06:53 UTC, HeHelee commented on src/api/hooks/fetchWishList.ts
> +export const useRemoveWish = () => {
넵 반영했습니다.

2024-07-29 06:58 UTC, HeHelee commented on src/api/hooks/fetchWishList.ts
> +      queryClient.invalidateQueries({ queryKey: ['wishList'] });
넵 반영했습니다.

2024-07-29 07:09 UTC, HeHelee commented on src/pages/FavoritesPage/index.tsx
> +          <List spacing={3}>
넵 if ~ else문으로 개선했습니다

2024-07-29 07:16 UTC, HeHelee commented on src/components/features/Order/OrderForm/Order.test.tsx
> +  test('폼이 초기 값으로 렌더링 되는지 확인', async () => {
넵 반영했습니다 ㅎㅎ

2024-07-29 07:16 UTC, HeHelee commented on src/components/features/Order/OrderForm/Order.test.tsx
> +import { fireEvent, render, screen, waitFor } from '@testing-library/react';
찾아서 notion에 정리해두겠습니다 !

2024-07-29 07:17 UTC, HeHelee commented
다시 수정해서 pr올리겠습니당

2024-07-30 16:12 UTC, yujo11 commented on src/api/hooks/fetchWishList.ts
> +export const useWishList = (page: number = 0, size: number = 10) => {
useQuery를 사용해서 선언하는 hook들은 보통 options를 사용하는 곳에서 결정하도록 parameter를 통해 option이 결정되도록 구현 하는거 같아요

hook의 목적을 생각해보면 아래 2가지 키워드가 먼저 떠오르는데요

1. 로직을 캡슐화하고
2. 재사용성을 높인다

options를 parameter로 받게 되면 1번의 목적 뿐만 아니라 2번의 목적에도 부합하는 유연한 hook이 될거 같아요

2024-07-30 16:13 UTC, yujo11 approved these changes
고생 많으셨습니다 희원님~~~ 👍 👍 👍

2024-07-30 16:13 UTC, merged