강원대 FE_이채연 5주차 과제 - 1단계
kakao-tech-campus-2nd-step2/react-product-login pull request #62
Opened 2024-07-26 13:11 UTC by codus1718

2024-07-26 15:58 UTC, codus1718 commented
![스크린샷 2024-07-27 005715](https://github.com/user-attachments/assets/9633f4f9-acaf-4f47-9824-90b0bcb6cd99)
저도 이 질문이 있어서 2단계를 제대로 수행했는지 모르겠습니다...ㅠ api가 없이도 되는데 제가 해결을 못한건지, 제가 수행한 과제가 맞는지 확신이 없어서 일단 리뷰요청 드립니다ㅠㅠ

2024-07-27 14:04 UTC, lazy-sky commented on src/components/WishList/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
any여야만 하는 이유가 있나요?

2024-07-27 14:05 UTC, lazy-sky commented on src/components/WishList/index.tsx
> +    const fetchWishList = async () => {
페칭 함수는 하드코딩보다는 따로 선언하는 편이 좋아보입니다.

2024-07-27 14:09 UTC, lazy-sky requested changes
안녕하세요, 채연님

일단 서버 db를 이용할 수 없는 상황이라면 말씀하신 방법이 최선으로 보입니다.

모킹 등 테스트 코드의 복잡한 부분까지 잘 작성해주셨네요. 수고하셨습니다!

2024-07-27 14:09 UTC, lazy-sky commented on src/__test__/GoodsDetail.test.tsx
> +    render(
아래 코드의 내용과 it에서 서술하는 내용이 어떤 식으로 호응하는 지 설명해주실 수 있나요?

2024-07-31 13:33 UTC, merged