강원대 FE_최서린 5주차 과제
kakao-tech-campus-2nd-step2/react-product-login pull request #63
Opened 2024-07-26 13:34 UTC by seorinnn

안녕하세요 멘토님!
현재 step1 과제는 수행하였고,
step2, step3 과제는 아직 진행중입니다!
항상 피드백 해주셔서 감사합니다 ㅎㅎ

궁금한 점이 하나 있는데,
msw 설정이나 jest 환경설정을 추가하는 등의 변경사항이 있는 경우,
커밋 메시지의 말머리를 `feat`로 작성하는 것과 `chore`로 작성하는 것 중
어떤 것이 조금 더 알맞은 커밋 메시지인지 궁금합니다!

2024-07-27 14:15 UTC, lazy-sky requested changes
안녕하세요, 서린님

MSW 설정 추가 또는 Jest 환경 설정 등은 새로운 기능이나 사용자를 위한 개선 사항이라기보단 개발 환경의 유지 보수이기 때문에 chore가 더 적합할 것으로 보입니다.

여러 엣지 케이스를 생각해서 테스트 케이스를 잘 작성해주신 것 같습니다. 수고하셨습니다!

2024-07-27 14:15 UTC, lazy-sky commented on src/pages/Goods/Detail/GoodsDetailPage.test.tsx
> +test('상품 상세페이지가 올바르게 렌더링된다.', async () => {
올바르게 렌더링된다는 말은 다소 추상적인 것 같습니다. 정확히 어떤 화면을 기대하는지 작성하면 더 좋을 것 같습니다.

2024-07-27 14:15 UTC, lazy-sky commented on src/pages/Order/OrderForm.test.tsx
> +beforeAll(() => {
이 코드는 무엇을 위한 선작업인가요?

2024-07-29 06:21 UTC, seorinnn commented on src/pages/Order/OrderForm.test.tsx
> +beforeAll(() => {
처음 코드를 작성할 때에는 이 선작업에 대해 크게 신경쓰지 못했는데,
코치님의 피드백으로 이 부분에 대해 다시 공부해보았습니다.

```
beforeAll(() => {
  window.alert = jest.fn();
});
```

우선 `beforeAll` 블록 안에 작성된 코드는 해당 테스트 스위트의 모든 테스트가 시작되기 전에 한 번 실행된다고 합니다.

그리고 `jest.fn()` 으로 생성된 모의함수는 해당 함수가 호출될 때마다 함수의 호출 여부, 호출된 인수 등을 검사할 수 있다고 합니다. 그래서 `window.alert` 처럼 테스트 환경에서 제대로 동작하지 않을 가능성이 있는 브라우저 내장 함수 호출 여부 등에 대해 문제없이 테스트할 수 있기 때문에 선작업으로 `window.alert` 함수를 모킹해주었습니다.

2024-07-29 06:22 UTC, seorinnn commented
아직 완벽하지는 않지만 step2 를 수행해보았습니다.
또한 처음 피드백해주셨던 부분 수정하고 코멘트 달아두었습니다 ㅎㅎ
감사합니다!

2024-07-29 06:25 UTC, seorinnn commented on src/pages/Goods/Detail/GoodsDetailPage.test.tsx
> +test('상품 상세페이지가 올바르게 렌더링된다.', async () => {
상품 이미지, 이름, 가격, 안내문이 렌더링되는지 확인하는 테스트이기 때문에
'상품 상세페이지에 상품 이미지, 이름, 가격, 안내문이 올바르게 렌더링된다.'
로 수정하였습니다! 

혹시 더 좋은 테스트명이나, 일반적으로 사용되는 테스트명 짓기 방식이 있다면 말씀해주시면 감사하겠습니다 ㅎㅎ

2024-07-29 06:41 UTC, lazy-sky commented on src/pages/Goods/Detail/GoodsDetailPage.test.tsx
> +test('상품 상세페이지가 올바르게 렌더링된다.', async () => {
테스트코드는 given, when, then을 생각하시고 그것이 잘 드러나도록 작성하시면 좋습니다.

2024-07-29 06:43 UTC, merged