강원대 FE_이예지 STEP2 제출합니다.
kakao-tech-campus-2nd-step2/react-product-login pull request #64
Opened 2024-07-26 13:37 UTC by yeahzee0421

안녕하세요 멘토님!
MSW를 사용해서 로그인, 회원가입 기능과 위시리스트 기능을 구현해보았습니다.
처음에 MSW 실행이 안되어서 헤맸다가 `npm run start:mock` 명령어를 실행하면, 환경 변수 `REACT_APP_RUN_MSW`가 `true`로 설정되어 start 스크립트가 실행되는 것을 발견하고, 원활하게 코드를 구현할 수 있었습니다 :D 

사용자가 '관심' 버튼을 누르면 위시리스트에 해당 상품이 담기도록 구현했습니다.
- 로그인한 사용자만 위시리스트에 담을 수 있도록 로그인 여부를 체크하는 로직을 추가했습니다.
- 위시리스트에 담은 상품 정보는 `sessionStorage`에 저장했습니다.
![image](https://github.com/user-attachments/assets/30ae50e1-a7e3-43a1-a8d5-0e93a0ba9cf8)

내 계정 페이지에서 위시리스틀 볼 수 있고,
![image](https://github.com/user-attachments/assets/3ff58241-d1ec-426d-8637-412af98bea1f)
삭제 버튼을 눌러 위시리스트에서 상품을 삭제할 수 있도록 구현했습니다.
- `filter` 메서드를 사용해서 삭제한 상품의 id를 위시리스트에서 제외합니다. 해당 리스트는 `updatedList` 변수에 담깁니다.
- 업데이트된 위시리스트 정보는 storage에 `set` 메서드로 갱신해주었습니다.

2024-07-27 12:08 UTC, yujo11 commented
잠시 닫았다가 다시 열겠습니다!

2024-07-27 12:19 UTC, yujo11 approved these changes
고생 많으셨습니다 예지님~~ 소소한 코멘트들 몇 개 남겼는데 확인해보시면 좋을거 같아요 ㅎㅎ

2024-07-27 12:19 UTC, yujo11 commented on src/components/features/Goods/Detail/OptionSection.tsx
> +      return navigate(getDynamicPath.login());
함수를 사용할 때 함수에서 반환되는 값이 존재하고, 해당 값을 사용할 때만 `return`을 사용하시면 좋을거 같아요 ㅎㅎ

2024-07-27 12:19 UTC, yujo11 commented on src/components/features/Goods/Detail/OptionSection.tsx
> +  const handleWishItem = () => {
하나의 함수에서 많은 일들이 발생하고 있는거 같은데 함수를 적절한 단위로 나눠보셔도 좋을거 같네요!

2024-07-27 12:19 UTC, yujo11 commented on src/pages/SignUp/index.tsx
> +      navigate(-1); //이전 로그인페이지로 이동
이전 페이지가 항상 로그인페이지인걸 보장해줄 수 있을까요?

2024-07-27 12:19 UTC, yujo11 requested changes
현재 conflict가 발생하고 있는데 resolve 부탁드립니다 ~~

2024-07-29 05:07 UTC, yeahzee0421 commented on src/pages/SignUp/index.tsx
> +      navigate(-1); //이전 로그인페이지로 이동
아 네 그렇네요 ..! 
`RouterPath.login` 을 사용해서 로그인 페이지로 확실히 연결되도록 수정했습니다.

2024-07-29 05:54 UTC, yeahzee0421 commented on src/components/features/Goods/Detail/OptionSection.tsx
> +  const handleWishItem = () => {
네 피드백 감사합니다.
하나의 함수가 최대한 하나의 일만 하도록 수정했습니다!

2024-07-29 06:06 UTC, yeahzee0421 commented on src/components/features/Goods/Detail/OptionSection.tsx
> +      return navigate(getDynamicPath.login());
넵:) 반영해서 리팩터링 했습니다 ㅎㅎ

2024-07-30 16:10 UTC, yujo11 approved these changes
고생많으셨습니다 예지님!

2024-07-30 16:11 UTC, merged