강원대 FE_윤채연 5주차 과제
kakao-tech-campus-2nd-step2/react-product-login pull request #85
Opened 2024-07-27 22:59 UTC by ychy61

안녕하세요 멘토님 5주차 과제 제출합니다.
항상 시간내어 피드백 해주셔서 감사합니다.
늦게 제출해서 죄송합니다.

테스트 코드를 처음 작성해 많이 낯설어 gpt나 다른 코드를 참고해보며 작성을 하였습니다. 
그런데 test를 할 때, 아래 이미지와 같이 module을 찾을 수가 없다는 오류가 발생하여 이를 해결하기 위해 시간이 오래 걸렸습니다. 그런데 아직도 이 오류를 해결하지 못하였습니다.... 분명 경로를 맞게 설정해주었는데 왜 아래와 같은 오류가 나는지 원인을 잘 모르겠습니다..
![image](https://github.com/user-attachments/assets/e42b8efa-548c-4ff6-adae-6a7d82bf49d8)

그럼 항상 감사합니다.

2024-07-28 10:27 UTC, yujo11 requested changes
안녕하세요 채연님 코드레벨에서 크게 남길만한 부분은 없는거 같은데요

본문에 남겨주신 모듈을 찾아오지 못 하는 부분은 테스트코드가 동작할 때 절대 경로(`@/`)를 제대로 해석하지 못 해서 생기는 문제일 수 있겠다는 생각이 들어요. 테스트 파일에서도 절대경로를 해석할 수 있는 설정을 추가해보셔도 좋을거 같아요

다른 분들의 PR을 참고해보셔도 좋겠네요! 고생 많으셨습니다 ~~

2024-07-28 10:27 UTC, yujo11 commented on src/tests/GoodsDetail.test.tsx
> +import userEvent from '@testing-library/user-event';
오 userEvent를 사용하셨군요 👍 👍 👍

2024-07-28 14:17 UTC, ychy61 commented
멘토님 피드백 감사합니다! 피드백을 참고하여 jest의 절대경로를 해석할 수 있도록 moduleNameMapper  사용하였더니 에러가 해결 되었습니다.

2024-07-28 16:41 UTC, ychy61 commented
우선 step3의 퀴즈 답 먼저 제출하겠습니다.

step2도 진행되면 pr 남기겠습니다.

감사합니다!

2024-07-28 20:30 UTC, yujo11 approved these changes
고생 많으셨습니다 채연님~~~!

2024-07-28 20:30 UTC, yujo11 commented on README.md
> +> 테스트가 있으면 코드 변경 시 기존 기능이 올바르게 작동하는지 빠르게 확인할 수 있는 것이 좋았습니다. 아쉬운 점은 초기에 테스트 코드를 작성하는 데 시간이 많이 소요된 것과 모든 케이스를 고려하여 테스트를 작성하는 것이 어려웠습니다.
테스트 코드를 작성하는게 익숙하지 않으면 초반에는 많은 시간이 걸릴 수 밖에 없는데요.

테스트 코드 작성에 익숙해지면 테스트 코드 작성에 드는 시간을 많이 줄이실 수 있을거에요! 화이팅입니다~~

2024-07-28 20:30 UTC, yujo11 commented on src/tests/GoodsDetail.test.tsx
> +  price: 145000,
소소하게 큰 숫자는 numeric separtor를 사용해주시면 보기 좋을거 같네요!
```suggestion
  price: 145_000,
```

2024-07-28 20:30 UTC, merged

2024-07-30 05:42 UTC, ychy61 commented on src/tests/GoodsDetail.test.tsx
> +  price: 145000,
넵 감사합니다!